### PR TITLE
feat(cl_gasmask): simplify control sequences

### PR DESCRIPTION
**Pull request by MM-coder**
Note that 

```lua
 CurrentMaskID = GetPedDrawableVariation(PlayerPedId(),1)
		if IsValidMask(CurrentMaskID) then
			wearingMask = true
		else
			wearingMask = false
```

Can be simplified to 

```lua
CurrentMaskID = GetPedDrawableVariation(PlayerPedId(),1)
wearingMask = IsValidMask(CurrentMaskID)
```

As `IsValidMask` returns a boolean.

### CODE REVIEW

**Comment by MM-coder** [comment]
Commits [2db21d0](https://github.com/theskiratta/calirp-gasmask/pull/2/commits/2db21d0612e217f7b77445e3c75d9aa385a955b4) and [56154d3](https://github.com/theskiratta/calirp-gasmask/pull/2/commits/56154d3d1248fb57fdb53e06dc379246c4bb0796) insert multiple, much-needed formatting changes to comply with the LUA spec

**Comment by MM-coder** [comment]
Note that in [285cf69](https://github.com/theskiratta/calirp-gasmask/pull/2/commits/285cf692cc44a9180c21650925ec92306788f1b7) the only major change is, that akin to Python, LUA allows two variables to be assigned at once if the value is the same.

**Review by MM-coder — COMMENTED** [review]
LGTM!

**Comment by theskiratta** [comment]
Thank you very much for the interesting PR, will merge

**Pull request merged**
